---
name: "GitHub yamllint check env return"
description: "Run yamllint with GitHub formatted output and environment variable output in YAML_LINT_OUT."
author: "Thijs Kaper"
branding:
  icon: "check-square"
  color: "green"
runs:
  using: 'docker'
  image: docker://ghcr.io/atkaper/yamllint-action:1.3.0
